export const documentPage = {
  quotes: 'Котировка акции',
  actives: 'Оборотные активы',
  averageProfit: 'Средняя прибыль',
  currentAssets: 'Текущие активы',
  equity: 'Собственный капитал',
  currentRevenue: 'Выручка(Отчет)',
  lastYearRevenue: 'Выручка за прошлый год',
  profit: 'Прибыль(Отчет)',
  quarterlyProfit: 'Прибыль квартальная',
  quarterlyRevenue: 'Выручка квартальная',
  returnOnEquity: 'Рентабельность собственного капитала, %',
  shareOfEquityInAssets: 'Доля собственного капитала в активах, %',
  yearSlidingProfit: 'Прибыль за год (скользящая)',
  yearSlidingRevenue: 'Выручка за год (скользящая)',

  fixedAssets: 'Основные средства',
  netCashFlowFromOperatingActivities: 'Денежный поток от операционной деятельности',
  noncurrentAssets: 'Внеоборотные активы',
  currentAssetsBalance: 'Оборотные активы',
  assetsBalance: 'Активы',
  equityBalance: 'Собственный капитал',
  noncurrentLiabilities: 'Долгосрочные обязательства',
  currentLiabilities: 'Текущие обязательства',
  liabilities: 'Обязательства',
  redeemableNoncontrollingInterest: 'Подлежащая погашению неконтролирующая доля',
  liabilitiesAndEquity: 'Обязательства и капитал',
  equityAttributableToParent: 'Акционерный капитал, относящийся к материнской компании',
  equityAttributableToNoncontrollingInterest: 'Собственный капитал, относящийся к неконтролирующей доле',
  otherThanFixedNoncurrentAssets: 'Кроме основных внеоборотных активов',



  revenues: 'Выручка (Квартальная)',
  costOfRevenue: 'Себестоимость продаж',
  grossProfit: 'Валовая прибыль',
  operatingExpenses: 'Операционные расходы',
  operatingIncomeLoss: 'Операционная прибыль/убыток',
  interestExpenseOperating: 'Процентные расходы',
  incomeLossFromContinuingOperationsBeforeTax: 'Прибыль/убыток от деятельности до налогообложения',
  netIncomeLoss: 'Прибыль (Квартальная)',
  incomeLossFromContinuingOperationsAfterTax: 'Прибыль/убыток от деятельности после налогообложения',
  netIncomeLossAttributableToNoncontrollingInterest: 'Чистая прибыль/убыток, относящиеся к неконтролируемым долям',
  netIncomeLossAvailableToCommonStockholdersBasic: 'Чистая прибыль/убыток, доступная держателям обыкновенных акций',
  participatingSecuritiesDistributedAndUndistributedEarningsLossBasic: 'Дивиденды по привилегированным акциям и др. корректировки',
  dilutedEarningsPerShare: 'Разводненная прибыль на акцию',
  basicEarningsPerShare: 'Базовая прибыль на акцию',
  otherComprehensiveIncomeLossAttributableToParent: 'Прочий совокупный доход/убыток, приходящийся на материнскую компанию',
  comprehensiveIncomeLossAttributableToNoncontrollingInterest: 'Совокупный доход/убыток, относящийся к неконтролирующей доле',
  comprehensiveIncomeLoss: 'Совокупный доход/убыток',
  comprehensiveIncomeLossAttributableToParent: 'Совокупный доход/убыток, приходящийся на материнскую компанию',



  netCashFlowFromOperatingActivitiesContinuing: 'Денежный поток от операционной деятельности',
  netCashFlowFromInvestingActivitiesContinuing: 'Денежный поток от инвестиционной деятельности',
  netCashFlowFromFinancingActivitiesContinuing: 'Денежный поток от финансовой деятельности',
  netCashFlow: 'Денежный поток от финансовой деятельности',

};
