export const documentPage = {
  quotes: 'Quotes',
  actives: 'Current assets',
  averageProfit: 'Average profit',
  currentAssets: 'Current assets',
  currentRevenue: 'Current revenue',
  equity: 'Equity capital',
  lastYearRevenue: 'Last year revenue',
  profit: 'Profit(Report)',
  quarterlyProfit: 'Quarterly profit',
  quarterlyRevenue: 'Quarterly revenue',
  returnOnEquity: 'Return on equity',
  shareOfEquityInAssets: 'Share of equity in assets',
  yearSlidingProfit: 'Year sliding profit',
  yearSlidingRevenue: 'Year sliding revenue',

  fixedAssets: '[EN]Основные средства',
  netCashFlowFromOperatingActivities: '[EN]Денежный поток от операционной деятельности',
  noncurrentAssets: '[EN]Внеоборотные активы',
  currentAssetsBalance: '[EN]Оборотные активы',
  assetsBalance: '[EN]Активы',
  equityBalance: '[EN]Собственный капитал',
  noncurrentLiabilities: '[EN]Долгосрочные обязательства',
  currentLiabilities: '[EN]Текущие обязательства',
  liabilities: '[EN]Обязательства',
  redeemableNoncontrollingInterest: '[EN]Подлежащая погашению неконтролирующая доля',
  liabilitiesAndEquity: '[EN]Обязательства и капитал',
  equityAttributableToParent: '[EN]Акционерный капитал, относящийся к материнской компании',
  equityAttributableToNoncontrollingInterest: '[EN]Собственный капитал, относящийся к неконтролирующей доле',
  otherThanFixedNoncurrentAssets: '[EN]Кроме основных внеоборотных активов',



  revenues: '[EN]Выручка (Квартальная)',
  costOfRevenue: '[EN]Себестоимость продаж',
  grossProfit: '[EN]Валовая прибыль',
  operatingExpenses: '[EN]Операционные расходы',
  operatingIncomeLoss: '[EN]Операционная прибыль/убыток',
  interestExpenseOperating: '[EN]Процентные расходы',
  incomeLossFromContinuingOperationsBeforeTax: '[EN]Прибыль/убыток от деятельности до налогообложения',
  netIncomeLoss: '[EN]Прибыль (Квартальная)',
  incomeLossFromContinuingOperationsAfterTax: '[EN]Прибыль/убыток от деятельности после налогообложения',
  netIncomeLossAttributableToNoncontrollingInterest: '[EN]Чистая прибыль/убыток, относящиеся к неконтролируемым долям',
  netIncomeLossAvailableToCommonStockholdersBasic: '[EN]Чистая прибыль/убыток, доступная держателям обыкновенных акций',
  participatingSecuritiesDistributedAndUndistributedEarningsLossBasic: '[EN]Дивиденды по привилегированным акциям и др. корректировки',
  dilutedEarningsPerShare: '[EN]Разводненная прибыль на акцию',
  basicEarningsPerShare: '[EN]Базовая прибыль на акцию',
  otherComprehensiveIncomeLossAttributableToParent: '[EN]Прочий совокупный доход/убыток, приходящийся на материнскую компанию',
  comprehensiveIncomeLossAttributableToNoncontrollingInterest: '[EN]Совокупный доход/убыток, относящийся к неконтролирующей доле',
  comprehensiveIncomeLoss: '[EN]Совокупный доход/убыток',
  comprehensiveIncomeLossAttributableToParent: '[EN]Совокупный доход/убыток, приходящийся на материнскую компанию',




  netCashFlowFromOperatingActivitiesContinuing: '[EN]Денежный поток от операционной деятельности',
  netCashFlowFromInvestingActivitiesContinuing: '[EN]Денежный поток от инвестиционной деятельности',
  netCashFlowFromFinancingActivitiesContinuing: '[EN]Денежный поток от финансовой деятельности',
  netCashFlow: '[EN]Денежный поток от финансовой деятельности',
};
